### PR TITLE
telescope: fix use of potentially nil `ext` and export name

### LINKED ISSUE #1: telescope extension: does not work due to incorrectly named export + use of nil value
`lua/telescope/_extensions/attempt.lua` has the following issues:

- [line#8](https://github.com/m-demare/attempt.nvim/blob/main/lua/telescope/_extensions/attempt.lua#L8) attempts to concatenate a nil value - checks that `ext ~= ''`, but can get around this by checking for truthyness (`ext`, period).
- [line#49](https://github.com/m-demare/attempt.nvim/blob/main/lua/telescope/_extensions/attempt.lua#L49) incorrectly names the export to `attempts`, so the telescope extension doesn't work.

Submitting PR shortly if you are interested.

### PR DESCRIPTION
**Pull request by chrsm**
fixes #1 

- fix check against potentially nil `ext` in `entry_to_filename`
- fix export name of telescope extension

### CODE REVIEW

File: lua/telescope/_extensions/attempt.lua [hunk 1]
```diff
@@ -5,7 +5,7 @@ local action_state = require 'telescope.actions.state'
 local action_set = require 'telescope.actions.set'
 
 local function entry_to_filename(e)
-  return e.value.filename .. (e.value.ext ~= '' and ('.' .. e.value.ext) or '')
+  return e.value.filename .. (e.value.ext and ('.' .. e.value.ext) or '')
```
Comment (m-demare) [inline lua/telescope/_extensions/attempt.lua:8]: The issue here is that `''` is actually truthy in lua. You would need to use both conditions

**Comment by m-demare** [comment]
Oh also, now that i've tested it in a couple of PCs, I've found that for some reason the name of the export did work sometimes (in fact, on my main PC it did work). I'm not sure why that is, but there is a chance that someone is already using `:Telescope attempts` on a mapping. Does it work well for you if you leave both exports (`attempt` and `attempts`)? If so, I'd leave both so as to avoid breaking changes
Otherwise, I'd add a [breaking change notice](https://www.conventionalcommits.org/en/v1.0.0/#summary) to the commit msg, so packer will warn users when updating

File: lua/telescope/_extensions/attempt.lua (hunk 1 above)
Comment (chrsm) [reply lua/telescope/_extensions/attempt.lua:8]: Oh, duh. Thanks, will get this fixed up.

**Comment by chrsm** [comment]
> Oh also, now that i've tested it in a couple of PCs, I've found that for some reason the name of the export did work sometimes (in fact, on my main PC it did work). 

Is this due to how you're using it in [your dotfiles](https://github.com/m-demare/dotfiles/blob/master/vim/nvim/lua/config/attempt.lua#L10)? I used the one in the README which recommended `map('n', '<leader>al', 'Telescope attempt')`, which errors because it's not called attempt.

If I try to run `:Telescope attempt`, I get:

```
Error executing Lua callback: ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:193: attempt to call a nil value
stack traceback:
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:193: in function 'run_command'
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
        ...te/pack/packer/start/telescope.nvim/plugin/telescope.lua:109: in function <...te/pack/packer/start/telescope.nvim/plugin/telescope.lua:108>
```

And `:Telescope attempts` results in:

```
[telescope.run_command]: Unknown command
```

I'd be happy to file this as a breaking change, but at least according to the README it's more of a fixing one since nobody could have been using it correctly unless they used your config.

**Comment by chrsm** [comment]
Squashed changes + updated the commit to include `BREAKING CHANGE` in the footer as requested by convential-commits.

Also manually fixup'd some of the formatting changes that stylua introduced, my apologies for that.

File: lua/telescope/_extensions/attempt.lua (hunk 1 above)
Comment (chrsm) [reply lua/telescope/_extensions/attempt.lua]: Fixed and tested!

image

**Comment by chrsm** [comment]
BTW, apologies for the spam here - but if you'd prefer both exports (`attempts` and `attempt`) I'm happy to do that as well - your plugin your rules. :-)

**Comment by m-demare** [comment]
> Is this due to how you're using it in [your dotfiles](https://github.com/m-demare/dotfiles/blob/master/vim/nvim/lua/config/attempt.lua#L10)? I used the one in the README which recommended map('n', '<leader>al', 'Telescope attempt'), which errors because it's not called attempt.

That makes sense, my bad. Thanks a lot for the contribution!

**Review by m-demare — APPROVED** [review]
